### PR TITLE
Make benchmark comparison with Hyphenator.js fair

### PR DESCRIPTION
**Pull request by mnater**
Dear Bram

Thanks for pointing to Hyphenator.js in your awesome speech at CSSconf EU 2014.
Looking at hypher I found that the speed test in comparison with Hyphenator.js is quite outdated. So I created the updated below (I'm still a git-noob, so maybe something goes wrong).

Regards,
Mathias

* use the current version of Hyphenator.js (some changes where necessary to run in node, this also needs updated patterns)
* use replace("-") instead of replace("=") to create the wordlist (otherways Hyphenator.js calls itself recursively)
* disable storage in Hyphenator.js
* use hypher.hyphenateText instead of hypher.hyphenate (hyphenateText is more what Hyphenator.js actually does)

### CODE REVIEW

**Comment by bramstein** [comment]
Hi Mathias, good to hear from you! The benchmark is quite outdated indeed. It was written before you incorporated some ideas from Hypher into Hyphenator.js. It wrote it to see if I could create a faster hyphenation algorithm. These changes look good, but I would also be happy to remove the benchmark (it has served its purpose).

Let me know what you think.

**Comment by mnater** [comment]
Hi Bram

Thanks for your response. Please feel free to remove the benchmark, although I liked the competition ;-)

BTW: I don't use your code for pattern-trie creation anymore. In Hyphenator.js the trie is now backed by a (typed) array. This uses much less memory at similar speed (if I measured correctly). Use it for hypher if you like.

Regards,
Mathias

**Comment by bramstein** [comment]
Ah, using a typed array, that's interesting. I was working on a double array trie implementation (https://github.com/bramstein/datrie) to reduce memory usage, but haven't looked at it in a while. I'll have a look at your implementation, thanks!

**Comment by mnater** [comment]
Very interesting. Is your datrie based on "An Efficient Implementation of Trie Structures" by Aoe, Morimoto and Sato? (Just googled it…)
I haven't completely understood yet how it works but it looks more efficient regarding memory usage than my approach (which is based on Franklin Liangs proposal without the packing).
What I don't like regarding double array tries at first sight is the repositioning of values upon collision (which I suspect to happen very often with hyphenation patterns).
But I'll give it a try. Thanks for the hint.

**Comment by bramstein** [comment]
Yes it is based on that paper. It appears to be quite efficient with memory, though I haven't tested that thoroughly. A nice side effect of the approach is that the trie does not need to be built. It operates directly on the two (or three) arrays.

The collisions are an issue indeed, but that should only happen when you modify an existing trie. I think you can write an optimal double array trie from an existing object trie. I unfortunately haven't had any time for it lately though.

**Pull request merged**
